/**
 * Child Safety Integration V1 — localized copy (en/sk/de), identical key structure across locales
 * (asserted by the UI test). Content-free labels only. The console is a LOCAL SANDBOX.
 */
import type { Locale } from "@/i18n/config";

export interface IntegrationCopy {
  title: string; subtitle: string;
  unauthorized: { badge: string; title: string; body: string; cta: string };
  loading: string; errorTitle: string; errorBody: string; retry: string; backToConsole: string;
  sandboxBanner: string;
  notices: { privacy: string; noRawContent: string; noCredentials: string; noBypass: string; notSurveillance: string; noPrivateKey: string; riskNotGuilt: string; noAutoContact: string };
  sections: { partners: string; applications: string; installations: string; keys: string; subjects: string; sandbox: string; receipts: string; errors: string };
  labels: { partnerKey: string; displayName: string; environment: string; applicationKey: string; installationKey: string; status: string; keyVersion: string; algorithm: string; fingerprint: string; validFrom: string; validUntil: string; publicKey: string; pseudonymousSubject: string; protectedProfile: string; resultCode: string; receivedAt: string; canonicalSignal: string; policyDecision: string; empty: string };
  actions: { createPartner: string; createApplication: string; createInstallation: string; registerKey: string; rotateKey: string; revokeKey: string; suspend: string; reactivate: string; linkSubject: string; validate: string; sandboxSend: string; confirm: string; cancel: string; working: string };
  builder: { title: string; signalType: string; confidenceBand: string; severityHint: string; immediateDanger: string; run: string; result: string; noRawFieldNote: string };
  statusLabel: Record<string, string>;
  resultLabel: Record<string, string>;
  errorRef: Record<string, string>;
}

const status = {
  en: { active: "Active", suspended: "Suspended", revoked: "Revoked", rotating: "Rotating" },
  sk: { active: "Aktívny", suspended: "Pozastavený", revoked: "Odvolaný", rotating: "Rotuje sa" },
  de: { active: "Aktiv", suspended: "Ausgesetzt", revoked: "Widerrufen", rotating: "Rotiert" },
};
const result = {
  en: { SIGNAL_ACCEPTED: "Accepted", SIGNAL_DUPLICATE: "Duplicate (idempotent)", RATE_LIMITED: "Rate limited", SIGNATURE_INVALID: "Signature invalid", NONCE_REPLAYED: "Replay blocked", IDEMPOTENCY_CONFLICT: "Idempotency conflict", PAYLOAD_INVALID: "Payload invalid", KEY_REVOKED: "Key revoked", TIMESTAMP_OUT_OF_WINDOW: "Timestamp out of window", PROTOCOL_UNSUPPORTED: "Protocol unsupported", CAPABILITY_DENIED: "Capability denied", INTEGRATION_UNKNOWN: "Unknown installation", INTEGRATION_SUSPENDED: "Suspended", PAYLOAD_TOO_LARGE: "Payload too large", INTEGRATION_AUTH_REQUIRED: "Authentication required", INTERNAL_FAIL_CLOSED: "Failed closed" },
  sk: { SIGNAL_ACCEPTED: "Prijaté", SIGNAL_DUPLICATE: "Duplikát (idempotentné)", RATE_LIMITED: "Obmedzené", SIGNATURE_INVALID: "Neplatný podpis", NONCE_REPLAYED: "Opakovanie blokované", IDEMPOTENCY_CONFLICT: "Konflikt idempotencie", PAYLOAD_INVALID: "Neplatný obsah", KEY_REVOKED: "Kľúč odvolaný", TIMESTAMP_OUT_OF_WINDOW: "Časová značka mimo okna", PROTOCOL_UNSUPPORTED: "Nepodporovaný protokol", CAPABILITY_DENIED: "Zamietnutá schopnosť", INTEGRATION_UNKNOWN: "Neznáma inštalácia", INTEGRATION_SUSPENDED: "Pozastavené", PAYLOAD_TOO_LARGE: "Obsah príliš veľký", INTEGRATION_AUTH_REQUIRED: "Vyžaduje sa autentifikácia", INTERNAL_FAIL_CLOSED: "Zlyhalo bezpečne" },
  de: { SIGNAL_ACCEPTED: "Akzeptiert", SIGNAL_DUPLICATE: "Duplikat (idempotent)", RATE_LIMITED: "Ratenbegrenzt", SIGNATURE_INVALID: "Signatur ungültig", NONCE_REPLAYED: "Replay blockiert", IDEMPOTENCY_CONFLICT: "Idempotenzkonflikt", PAYLOAD_INVALID: "Nutzdaten ungültig", KEY_REVOKED: "Schlüssel widerrufen", TIMESTAMP_OUT_OF_WINDOW: "Zeitstempel außerhalb", PROTOCOL_UNSUPPORTED: "Protokoll nicht unterstützt", CAPABILITY_DENIED: "Fähigkeit verweigert", INTEGRATION_UNKNOWN: "Unbekannte Installation", INTEGRATION_SUSPENDED: "Ausgesetzt", PAYLOAD_TOO_LARGE: "Nutzdaten zu groß", INTEGRATION_AUTH_REQUIRED: "Authentifizierung erforderlich", INTERNAL_FAIL_CLOSED: "Sicher fehlgeschlagen" },
};
const errRef = {
  en: { SIGNATURE_INVALID: "The request signature did not verify against the installation key.", NONCE_REPLAYED: "This nonce was already used — replay is blocked.", IDEMPOTENCY_CONFLICT: "The idempotency key was reused with a different payload.", TIMESTAMP_OUT_OF_WINDOW: "sentAt is outside the allowed clock-skew window.", RATE_LIMITED: "Too many requests for this installation. Retry after the delay.", PAYLOAD_INVALID: "The signal payload failed strict validation.", KEY_REVOKED: "The signing key is revoked or expired." },
  sk: { SIGNATURE_INVALID: "Podpis požiadavky sa neoveril voči kľúču inštalácie.", NONCE_REPLAYED: "Tento nonce už bol použitý — opakovanie je blokované.", IDEMPOTENCY_CONFLICT: "Kľúč idempotencie bol použitý s iným obsahom.", TIMESTAMP_OUT_OF_WINDOW: "sentAt je mimo povoleného okna odchýlky času.", RATE_LIMITED: "Príliš veľa požiadaviek pre túto inštaláciu. Skúste po oneskorení.", PAYLOAD_INVALID: "Obsah signálu neprešiel prísnou validáciou.", KEY_REVOKED: "Podpisový kľúč je odvolaný alebo vypršal." },
  de: { SIGNATURE_INVALID: "Die Signatur wurde nicht gegen den Installationsschlüssel verifiziert.", NONCE_REPLAYED: "Dieser Nonce wurde bereits verwendet — Replay ist blockiert.", IDEMPOTENCY_CONFLICT: "Der Idempotenzschlüssel wurde mit anderen Nutzdaten wiederverwendet.", TIMESTAMP_OUT_OF_WINDOW: "sentAt liegt außerhalb des erlaubten Zeitfensters.", RATE_LIMITED: "Zu viele Anfragen für diese Installation. Nach Verzögerung erneut versuchen.", PAYLOAD_INVALID: "Die Signal-Nutzdaten haben die strenge Validierung nicht bestanden.", KEY_REVOKED: "Der Signaturschlüssel ist widerrufen oder abgelaufen." },
};

function build(l: "en" | "sk" | "de", t: Omit<IntegrationCopy, "statusLabel" | "resultLabel" | "errorRef">): IntegrationCopy {
  return { ...t, statusLabel: status[l], resultLabel: result[l], errorRef: errRef[l] };
}

export const INTEGRATION_COPY: Record<Locale, IntegrationCopy> = {
  en: build("en", {
    title: "Child Safety Integration Sandbox", subtitle: "Register authorized partners and test the minimal safety-signal protocol locally.",
    unauthorized: { badge: "403 · Access denied", title: "Integration access required", body: "This console is limited to workspace owners, administrators, and safety reviewers.", cta: "Back to console" },
    loading: "Loading…", errorTitle: "Something went wrong", errorBody: "The integration console couldn't load. Please try again.", retry: "Try again", backToConsole: "Reviewer console",
    sandboxBanner: "LOCAL SANDBOX — synthetic data only. No production credentials, no real child data, no raw messages.",
    notices: { privacy: "Partners send only a minimal, content-free structured safety signal.", noRawContent: "Raw communications never leave the partner platform — Tamanor never receives message content.", noCredentials: "Tamanor never requests platform credentials, passwords, tokens, or session cookies.", noBypass: "Tamanor never bypasses Meta or any other platform.", notSurveillance: "This is not a surveillance SDK — it does not read device notifications, screens, or private messages.", noPrivateKey: "Partners hold their own private key; Tamanor stores only public keys.", riskNotGuilt: "A signal describes a detected risk pattern, not proven guilt.", noAutoContact: "No authority or guardian is contacted automatically; partner authorization is mandatory." },
    sections: { partners: "Partners", applications: "Applications", installations: "Installations", keys: "Public keys", subjects: "Subject links", sandbox: "Synthetic signal", receipts: "Receipts", errors: "Error codes" },
    labels: { partnerKey: "Partner key", displayName: "Display name", environment: "Environment", applicationKey: "Application key", installationKey: "Installation key", status: "Status", keyVersion: "Key version", algorithm: "Algorithm", fingerprint: "Fingerprint", validFrom: "Valid from", validUntil: "Valid until", publicKey: "Public key (base64 SPKI)", pseudonymousSubject: "Pseudonymous subject", protectedProfile: "Protected profile", resultCode: "Result", receivedAt: "Received", canonicalSignal: "Canonical signal", policyDecision: "Policy decision", empty: "None yet." },
    actions: { createPartner: "Add partner", createApplication: "Add application", createInstallation: "Add installation", registerKey: "Register public key", rotateKey: "Rotate", revokeKey: "Revoke", suspend: "Suspend", reactivate: "Reactivate", linkSubject: "Link subject", validate: "Validate", sandboxSend: "Send sandbox signal", confirm: "Confirm", cancel: "Cancel", working: "Working…" },
    builder: { title: "Synthetic signal builder", signalType: "Risk type", confidenceBand: "Confidence", severityHint: "Severity hint", immediateDanger: "Immediate danger", run: "Run", result: "Result", noRawFieldNote: "There is no message/content field — only bounded, content-free codes." },
  }),
  sk: build("sk", {
    title: "Sandbox integrácie ochrany detí", subtitle: "Registrujte autorizovaných partnerov a testujte protokol minimálnych bezpečnostných signálov lokálne.",
    unauthorized: { badge: "403 · Prístup zamietnutý", title: "Vyžaduje sa prístup k integrácii", body: "Táto konzola je len pre vlastníkov, administrátorov a bezpečnostných recenzentov.", cta: "Späť do konzoly" },
    loading: "Načítava sa…", errorTitle: "Niečo sa pokazilo", errorBody: "Konzolu integrácie sa nepodarilo načítať. Skúste znova.", retry: "Skúsiť znova", backToConsole: "Konzola recenzenta",
    sandboxBanner: "LOKÁLNY SANDBOX — len syntetické dáta. Žiadne produkčné poverenia, žiadne reálne detské dáta, žiadne surové správy.",
    notices: { privacy: "Partneri posielajú iba minimálny bezobsahový štruktúrovaný bezpečnostný signál.", noRawContent: "Surová komunikácia nikdy neopustí platformu partnera — Tamanor nikdy nedostane obsah správ.", noCredentials: "Tamanor nikdy nežiada poverenia platformy, heslá, tokeny ani cookies relácie.", noBypass: "Tamanor nikdy neobchádza Meta ani žiadnu inú platformu.", notSurveillance: "Toto nie je sledovacie SDK — nečíta upozornenia zariadenia, obrazovky ani súkromné správy.", noPrivateKey: "Partneri majú vlastný súkromný kľúč; Tamanor ukladá iba verejné kľúče.", riskNotGuilt: "Signál opisuje zistený vzorec rizika, nie dokázanú vinu.", noAutoContact: "Žiadny orgán ani opatrovník nie je kontaktovaný automaticky; autorizácia partnera je povinná." },
    sections: { partners: "Partneri", applications: "Aplikácie", installations: "Inštalácie", keys: "Verejné kľúče", subjects: "Prepojenia subjektov", sandbox: "Syntetický signál", receipts: "Potvrdenia", errors: "Kódy chýb" },
    labels: { partnerKey: "Kľúč partnera", displayName: "Zobrazovaný názov", environment: "Prostredie", applicationKey: "Kľúč aplikácie", installationKey: "Kľúč inštalácie", status: "Stav", keyVersion: "Verzia kľúča", algorithm: "Algoritmus", fingerprint: "Odtlačok", validFrom: "Platný od", validUntil: "Platný do", publicKey: "Verejný kľúč (base64 SPKI)", pseudonymousSubject: "Pseudonymný subjekt", protectedProfile: "Chránený profil", resultCode: "Výsledok", receivedAt: "Prijaté", canonicalSignal: "Kanonický signál", policyDecision: "Rozhodnutie politiky", empty: "Zatiaľ žiadne." },
    actions: { createPartner: "Pridať partnera", createApplication: "Pridať aplikáciu", createInstallation: "Pridať inštaláciu", registerKey: "Registrovať verejný kľúč", rotateKey: "Rotovať", revokeKey: "Odvolať", suspend: "Pozastaviť", reactivate: "Reaktivovať", linkSubject: "Prepojiť subjekt", validate: "Overiť", sandboxSend: "Odoslať sandbox signál", confirm: "Potvrdiť", cancel: "Zrušiť", working: "Pracuje sa…" },
    builder: { title: "Tvorca syntetického signálu", signalType: "Typ rizika", confidenceBand: "Dôvera", severityHint: "Návrh závažnosti", immediateDanger: "Okamžité nebezpečenstvo", run: "Spustiť", result: "Výsledok", noRawFieldNote: "Neexistuje pole správy/obsahu — iba ohraničené bezobsahové kódy." },
  }),
  de: build("de", {
    title: "Kinderschutz-Integrations-Sandbox", subtitle: "Autorisierte Partner registrieren und das minimale Sicherheitssignal-Protokoll lokal testen.",
    unauthorized: { badge: "403 · Zugriff verweigert", title: "Integrationszugriff erforderlich", body: "Diese Konsole ist auf Eigentümer, Administratoren und Sicherheitsprüfer beschränkt.", cta: "Zurück zur Konsole" },
    loading: "Wird geladen…", errorTitle: "Etwas ist schiefgelaufen", errorBody: "Die Integrationskonsole konnte nicht geladen werden. Bitte erneut versuchen.", retry: "Erneut versuchen", backToConsole: "Prüferkonsole",
    sandboxBanner: "LOKALE SANDBOX — nur synthetische Daten. Keine Produktions-Anmeldedaten, keine echten Kinderdaten, keine Rohnachrichten.",
    notices: { privacy: "Partner senden nur ein minimales, inhaltsfreies strukturiertes Sicherheitssignal.", noRawContent: "Rohkommunikation verlässt nie die Partnerplattform — Tamanor erhält nie Nachrichteninhalte.", noCredentials: "Tamanor fragt nie Plattform-Anmeldedaten, Passwörter, Tokens oder Sitzungscookies ab.", noBypass: "Tamanor umgeht nie Meta oder eine andere Plattform.", notSurveillance: "Dies ist kein Überwachungs-SDK — es liest keine Gerätebenachrichtigungen, Bildschirme oder privaten Nachrichten.", noPrivateKey: "Partner besitzen ihren eigenen privaten Schlüssel; Tamanor speichert nur öffentliche Schlüssel.", riskNotGuilt: "Ein Signal beschreibt ein erkanntes Risikomuster, keine erwiesene Schuld.", noAutoContact: "Keine Behörde oder Erziehungsberechtigte wird automatisch kontaktiert; Partnerautorisierung ist verpflichtend." },
    sections: { partners: "Partner", applications: "Anwendungen", installations: "Installationen", keys: "Öffentliche Schlüssel", subjects: "Subjektverknüpfungen", sandbox: "Synthetisches Signal", receipts: "Belege", errors: "Fehlercodes" },
    labels: { partnerKey: "Partnerschlüssel", displayName: "Anzeigename", environment: "Umgebung", applicationKey: "Anwendungsschlüssel", installationKey: "Installationsschlüssel", status: "Status", keyVersion: "Schlüsselversion", algorithm: "Algorithmus", fingerprint: "Fingerabdruck", validFrom: "Gültig ab", validUntil: "Gültig bis", publicKey: "Öffentlicher Schlüssel (base64 SPKI)", pseudonymousSubject: "Pseudonymes Subjekt", protectedProfile: "Geschütztes Profil", resultCode: "Ergebnis", receivedAt: "Empfangen", canonicalSignal: "Kanonisches Signal", policyDecision: "Richtlinienentscheidung", empty: "Noch keine." },
    actions: { createPartner: "Partner hinzufügen", createApplication: "Anwendung hinzufügen", createInstallation: "Installation hinzufügen", registerKey: "Öffentlichen Schlüssel registrieren", rotateKey: "Rotieren", revokeKey: "Widerrufen", suspend: "Aussetzen", reactivate: "Reaktivieren", linkSubject: "Subjekt verknüpfen", validate: "Validieren", sandboxSend: "Sandbox-Signal senden", confirm: "Bestätigen", cancel: "Abbrechen", working: "Wird ausgeführt…" },
    builder: { title: "Synthetischer Signal-Builder", signalType: "Risikotyp", confidenceBand: "Konfidenz", severityHint: "Schweregrad-Hinweis", immediateDanger: "Unmittelbare Gefahr", run: "Ausführen", result: "Ergebnis", noRawFieldNote: "Es gibt kein Nachrichten-/Inhaltsfeld — nur begrenzte, inhaltsfreie Codes." },
  }),
};
